# SPDX-FileCopyrightText: 2023 Rot127 <unisono@quyllur.org>
# SPDX-License-Identifier: LGPL-3.0-only

# Rizin's core is not thread save.
# We have no other choice then running tests sequencially.
[alias]
test_lib_seq = "test --lib -- --test-threads=1"

[build]
# Required because it uses ld by default. Which breaks the build on some Linux dists
# See: https://users.rust-lang.org/t/enabling-rust-lld-for-aarch64-unknown-linux-gnu/113243/5
rustflags = ["-C", "link-arg=-fuse-ld=lld"]
