# SPDX-FileCopyrightText: 2023 Rot127 <unisono@quyllur.org>
# SPDX-License-Identifier: LGPL-3.0-only

# Rizin's core is not thread save.
# We have no other choice then running tests sequencially.
[alias]
test_seq = "test -- --test-threads=1"
